name: AdvancementCommand
version: ${project.version}
main: co.aikar.advancementcommand.AdvancementCommand
authors: [Aikar]
description: When an advancement is ran, run a command at potentially elevated permissions
website: https://aikar.co
